#!/usr/bin/env node
/**
 * One-shot generator for the country paths used by the onboarding
 * CountryPicker.vue map. Consumes a WGS84 GeoJSON of European countries,
 * projects the coordinates onto an SVG viewBox (equirectangular), and
 * writes a JS module that exports the paths.
 *
 * Run from repo root:
 *   node scripts/generate_europe_paths.mjs <path-to-europe.geojson>
 *
 * The committed output lives at
 *   app/javascript/dashboard/routes/dashboard/onboarding/countryPaths.js
 */

import fs from 'node:fs';
import path from 'node:path';

const VIEW_W = 800;
const VIEW_H = 700;

// Europe bounding box (lon_min, lon_max, lat_min, lat_max) that fits the
// countries we care about comfortably.
const LON_MIN = -12;
const LON_MAX = 32;
const LAT_MIN = 34;
const LAT_MAX = 72;

// Which countries to include. "active" + "expansion" + a few neighbouring
// "context" countries so the map doesn't have weird holes.
const ACTIVE = ['DE', 'FR', 'IT', 'FI', 'SE', 'NO', 'GB'];
const EXPANSION = ['NL', 'IE', 'ES', 'BE', 'CH', 'AT', 'DK', 'PL'];
const CONTEXT = [
  'PT', 'CZ', 'SK', 'HU', 'SI', 'HR', 'RO', 'BG', 'GR', 'AL',
  'MK', 'ME', 'RS', 'BA', 'LU', 'LI', 'EE', 'LV', 'LT',
  'IS', 'FO', 'AD', 'MC', 'SM', 'VA', 'MT', 'CY'
];
const KEEP = new Set([...ACTIVE, ...EXPANSION, ...CONTEXT]);

const project = ([lon, lat]) => {
  const x = ((lon - LON_MIN) / (LON_MAX - LON_MIN)) * VIEW_W;
  // SVG y grows downward; lat grows upward.
  const y = VIEW_H - ((lat - LAT_MIN) / (LAT_MAX - LAT_MIN)) * VIEW_H;
  return [x, y];
};

// Ramer–Douglas–Peucker polyline simplification. Keeps shape recognisable
// while dropping tiny oscillations that would otherwise bloat the SVG.
const rdp = (points, epsilon) => {
  if (points.length <= 2) return points;
  let maxDist = 0;
  let idx = 0;
  const [start, end] = [points[0], points[points.length - 1]];
  for (let i = 1; i < points.length - 1; i += 1) {
    const d = perpendicularDistance(points[i], start, end);
    if (d > maxDist) {
      maxDist = d;
      idx = i;
    }
  }
  if (maxDist > epsilon) {
    const left = rdp(points.slice(0, idx + 1), epsilon);
    const right = rdp(points.slice(idx), epsilon);
    return [...left.slice(0, -1), ...right];
  }
  return [start, end];
};

const perpendicularDistance = ([px, py], [ax, ay], [bx, by]) => {
  const dx = bx - ax;
  const dy = by - ay;
  if (dx === 0 && dy === 0) return Math.hypot(px - ax, py - ay);
  const t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy);
  const cx = ax + t * dx;
  const cy = ay + t * dy;
  return Math.hypot(px - cx, py - cy);
};

const ringToPath = (ring) => {
  const projected = ring.map(project);
  const simplified = rdp(projected, 0.6); // 0.6 SVG px tolerance ≈ cartographic 0.03°
  if (simplified.length < 3) return null;
  const [first, ...rest] = simplified;
  const body = rest.map(([x, y]) => `L${x.toFixed(1)} ${y.toFixed(1)}`).join('');
  return `M${first[0].toFixed(1)} ${first[1].toFixed(1)}${body}Z`;
};

const geometryToPath = (geometry) => {
  const pieces = [];
  const polygons = geometry.type === 'MultiPolygon'
    ? geometry.coordinates
    : [geometry.coordinates];
  for (const polygon of polygons) {
    // Drop tiny islands (< 0.005 area in projected units) for cleanliness.
    const outer = polygon[0];
    if (!outer || outer.length < 4) continue;
    const path = ringToPath(outer);
    if (path) pieces.push(path);
  }
  return pieces.join(' ');
};

const main = () => {
  const input = process.argv[2];
  if (!input) {
    console.error('Usage: node scripts/generate_europe_paths.mjs <europe.geojson>');
    process.exit(1);
  }
  const raw = fs.readFileSync(input, 'utf8');
  const geo = JSON.parse(raw);
  const out = {};
  for (const feature of geo.features) {
    const iso = feature.properties?.ISO2 || feature.properties?.iso_a2 || feature.properties?.iso;
    if (!iso || !KEEP.has(iso)) continue;
    const d = geometryToPath(feature.geometry);
    if (d) out[iso] = d;
  }
  const outPath = path.resolve(
    'app/javascript/dashboard/routes/dashboard/onboarding/countryPaths.js'
  );
  const header = `// AUTO-GENERATED by scripts/generate_europe_paths.mjs — do not hand-edit.
// Source: europe.geojson (WGS84) simplified to viewBox ${VIEW_W}×${VIEW_H}.
// ActiveCountries / ExpansionCountries / contextCountries sets live next to the component.

export const EU_MAP_VIEWBOX = '0 0 ${VIEW_W} ${VIEW_H}';

export const COUNTRY_PATHS = Object.freeze(${JSON.stringify(out, null, 2)});
`;
  fs.writeFileSync(outPath, header);
  const size = Buffer.byteLength(header, 'utf8');
  console.log(
    `Wrote ${Object.keys(out).length} countries (${(size / 1024).toFixed(1)} KB) → ${outPath}`
  );
};

main();
